; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs  | FileCheck %s

define i16 @argpass16(i16,i16,i16) #0  {
; CHECK-LABEL: argpass16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    RET

  %4 = alloca i16, align 1
  store i16 %2, i16* %4, align 1
  %5 = load i16, i16* %4, align 1
  ret i16 %5
}


define i8 @argpass8(i8,i8,i8)  {
; CHECK-LABEL: argpass8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    RET

  %4 = alloca i8, align 1
  store i8 %2, i8* %4, align 1
  %5 = load i8, i8* %4, align 1
  ret i8 %5
}
