; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

define i16 @add_sub_1(i16,i16) {
; CHECK-LABEL: add_sub_1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ADD E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADC D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ADD C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADC B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ADD C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADC B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ADD C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADC B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI D, 223
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SBB D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET

  %3 = add i16 %0, %1
  %4 = add i16 %3, %3
  %5 = add i16 %4, %4
  %6 = add i16 %5, %5
  %7 = sub i16 %6, 223
  ret i16 %7
}


define i16 @add_sub_2(i16,i16) {
; CHECK-LABEL: add_sub_2:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    ADD C
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ADC B
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    LXI B, 10000
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ADD C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADC B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI D, 3
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ADD E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADC D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET

  %3 = add i16 %0, %1
  %4 = sub i16 %3, 10000
  %5 = add i16 %4, %4
  %6 = add i16 3, %5
  ret i16 %6
}

define i8 @add_sub_3(i8,i8) {
; CHECK-LABEL: add_sub_3:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    ADD B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MVI A, 58
; CHECK-NEXT:    ADD B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET

  %3 = add i8 %0, %1 ; 48
  %4 = sub i8 100, %3 ; 52
  %5 = sub i8 54, %4 ; 2
  %6 = add i8 101, %5 ; 103
  %7 = add i8 3, %6 ;  106
  ret i8 %7
}


define i8 @add_sub_4(i8,i8) {
; CHECK-LABEL: add_sub_4:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 65534
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK-NEXT:    MVI A, 100
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    ADD B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    XRI -1
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MVI A, 6
; CHECK-NEXT:    ADD B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967294
; CHECK-NEXT:    RET

  %3 = alloca i8, align 1
  store i8 100, i8* %3, align 1
  %4 = load i8, i8* %3, align 1

  %5 = alloca i8, align 1
  store i8 %0, i8* %5, align 1
  %6 = load i8, i8* %5, align 1

  %7 = add i8 %4, %6
  %8 = sub i8 5 , %7

  %9 = alloca i8, align 1
  store i8 %8, i8* %9, align 1
  %10 = load i8, i8* %9, align 1

  ret i8 %10
}
