; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --function callee --version 5
; RUN: llc -O0 -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

%S = type { i8, i16, i8, i16 }

declare void @callee(ptr byval(%S) align 1)

define void @caller(ptr %p) {
; CHECK-LABEL: caller:
; CHECK:         .cfi_startproc
; CHECK:         LXI H, 65524
; CHECK:         SPHL
; CHECK:         CALL callee
; CHECK:         LXI H, 12
; CHECK:         SPHL
; CHECK:         RET
entry:
  call void @callee(ptr byval(%S) align 1 %p)
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
