; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Ensure stack argument placement uses distinct offsets before CALL.

define i8 @callee(i8 %a, i16 %b) {
; CHECK-LABEL: callee:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    ADD B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET
entry:
  %b8 = trunc i16 %b to i8
  %sum = add i8 %a, %b8
  ret i8 %sum
}

define i8 @caller(i8 %x, i16 %y) {
; CHECK-LABEL: caller:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 65533
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 3
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    STAX B
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL callee
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967293
; CHECK-NEXT:    RET
entry:
  %call = call i8 @callee(i8 %x, i16 %y)
  ret i8 %call
}
