; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 | FileCheck %s

; Comparison chain patterns: logical AND/OR of multiple comparisons.
; Adapted from RISC-V branch.ll patterns.

; Test: (a > 5) && (a < 100) -- range check
define i8 @cmp_chain_and_i16(i16 %a) {
; CHECK-LABEL: cmp_chain_and_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI D, 6
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA D
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB0_3
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SBB D
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    JC LBB0_6
; CHECK-NEXT:  LBB0_5: ; %entry
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JZ LBB0_7
; CHECK-NEXT:    JMP LBB0_17
; CHECK-NEXT:  LBB0_3: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB0_5
; CHECK-NEXT:  LBB0_6: ; %entry
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB0_17
; CHECK-NEXT:  LBB0_7: ; %entry
; CHECK-NEXT:    LXI D, 99
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA D
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB0_11
; CHECK-NEXT:  ; %bb.8: ; %entry
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    SBB D
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    JC LBB0_9
; CHECK-NEXT:  ; %bb.13: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CMP D
; CHECK-NEXT:    JNZ LBB0_19
; CHECK-NEXT:  ; %bb.14: ; %entry
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    CMP E
; CHECK-NEXT:    JZ LBB0_9
; CHECK-NEXT:  LBB0_19: ; %entry
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JZ LBB0_10
; CHECK-NEXT:  LBB0_17: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_11: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB0_19
; CHECK-NEXT:  LBB0_9: ; %entry
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB0_17
; CHECK-NEXT:  LBB0_10: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET
entry:
  %cmp1 = icmp sgt i16 %a, 5
  %cmp2 = icmp slt i16 %a, 100
  %and = and i1 %cmp1, %cmp2
  br i1 %and, label %t, label %f
t:
  ret i8 1
f:
  ret i8 0
}

; Test: (a == 0) || (a == 1) -- two-value check
define i8 @cmp_chain_or_i8(i8 %a) {
; CHECK-LABEL: cmp_chain_or_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CPI 0
; CHECK-NEXT:    JZ LBB1_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CPI 1
; CHECK-NEXT:    JZ LBB1_2
; CHECK-NEXT:  ; %bb.3: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB1_2: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET
entry:
  %cmp1 = icmp eq i8 %a, 0
  %cmp2 = icmp eq i8 %a, 1
  %or = or i1 %cmp1, %cmp2
  br i1 %or, label %t, label %f
t:
  ret i8 1
f:
  ret i8 0
}

; Test: (a != b) && (c != d) -- independent comparisons
define i8 @cmp_chain_indep(i16 %a, i16 %b, i16 %c, i16 %d) {
; CHECK-LABEL: cmp_chain_indep:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV H, M
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    CMP D
; CHECK-NEXT:    JNZ LBB2_4
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    CMP E
; CHECK-NEXT:    JZ LBB2_5
; CHECK-NEXT:  LBB2_4: ; %entry
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:  LBB2_5: ; %entry
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV H, M
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB2_10
; CHECK-NEXT:  ; %bb.6: ; %entry
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    CMP D
; CHECK-NEXT:    JNZ LBB2_12
; CHECK-NEXT:  ; %bb.7: ; %entry
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    CMP E
; CHECK-NEXT:    JZ LBB2_9
; CHECK-NEXT:  LBB2_12: ; %entry
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:  LBB2_9: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB2_10
; CHECK-NEXT:  ; %bb.13: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB2_10: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
entry:
  %cmp1 = icmp ne i16 %a, %b
  %cmp2 = icmp ne i16 %c, %d
  %and = and i1 %cmp1, %cmp2
  br i1 %and, label %t, label %f
t:
  ret i8 1
f:
  ret i8 0
}
