; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Signed i8 less-than select should use sign checks (XRA/ANI 128) and carry logic.

define i8 @cmp_slt_i8(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_slt_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB0_1
; CHECK-NEXT:    JNZ LBB0_4
; CHECK-NEXT:  LBB0_1:
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB B
; CHECK-NEXT:    JC LBB0_2
; CHECK-NEXT:  ; %bb.3:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_4:
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB0_5
; CHECK-NEXT:    JNZ LBB0_2
; CHECK-NEXT:  LBB0_5:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_2:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET

  %cmp = icmp slt i8 %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}

; Signed i8 greater-than select should also use sign checks.

define i8 @cmp_sgt_i8(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_sgt_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB1_1
; CHECK-NEXT:    JNZ LBB1_3
; CHECK-NEXT:  LBB1_1:
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB B
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    JZ LBB1_2
; CHECK-NEXT:    JNC LBB1_5
; CHECK-NEXT:  LBB1_2:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB1_3:
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB1_4
; CHECK-NEXT:    JNZ LBB1_2
; CHECK-NEXT:  LBB1_4:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:  LBB1_5:
; CHECK-NEXT:    RET

  %cmp = icmp sgt i8 %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}

; Signed i16 less-than select should check sign mismatch then do 16-bit subtract.

define i8 @cmp_slt_i16(i16 %a, i16 %b) {
; CHECK-LABEL: cmp_slt_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA D
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB2_3
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SBB D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    JNC LBB2_4
; CHECK-NEXT:  LBB2_2:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB2_3:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB2_2
; CHECK-NEXT:  LBB2_4:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET

  %cmp = icmp slt i16 %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}

; Unsigned i16 greater-or-equal should use carry from 16-bit subtract.

define i8 @cmp_uge_i16(i16 %a, i16 %b) {
; CHECK-LABEL: cmp_uge_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    JNC LBB3_1
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB3_1:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET

  %cmp = icmp uge i16 %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}

; Unsigned i8 greater-or-equal should use carry from subtract.

define i8 @cmp_uge_i8(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_uge_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    SUB B
; CHECK-NEXT:    JNC LBB4_1
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB4_1:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET

  %cmp = icmp uge i8 %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}
