; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Signed i8 less-than select should use sign checks (XRA/ANI 128) and carry logic.

define i8 @cmp_slt_i8(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_slt_i8:
; CHECK:       LBB0_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, H
; CHECK-NEXT:    MOV E, L
; CHECK-NEXT:    LDAX D
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB0_1
; CHECK-NEXT:    JNZ LBB0_3
; CHECK-NEXT:  LBB0_1:
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB B
; CHECK-NEXT:    JNC LBB0_5
; CHECK-NEXT:  LBB0_2:
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    JMP LBB0_6
; CHECK-NEXT:  LBB0_3:
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB0_4
; CHECK-NEXT:    JNZ LBB0_2
; CHECK-NEXT:  LBB0_4:
; CHECK-NEXT:  LBB0_5:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:  LBB0_6:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    POP D
; CHECK:    RET

  %cmp = icmp slt i8 %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}

; Signed i8 greater-than select should also use sign checks.

define i8 @cmp_sgt_i8(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_sgt_i8:
; CHECK:       LBB1_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, H
; CHECK-NEXT:    MOV E, L
; CHECK-NEXT:    LDAX D
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB1_1
; CHECK-NEXT:    JNZ LBB1_4
; CHECK-NEXT:  LBB1_1:
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB B
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    JZ LBB1_2
; CHECK-NEXT:    JNC LBB1_6
; CHECK-NEXT:  LBB1_2:
; CHECK-NEXT:  LBB1_3:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    JMP LBB1_6
; CHECK-NEXT:  LBB1_4:
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB1_5
; CHECK-NEXT:    JNZ LBB1_3
; CHECK-NEXT:  LBB1_5:
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:  LBB1_6:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    POP D
; CHECK:    RET

  %cmp = icmp sgt i8 %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}

; Signed i16 less-than select should check sign mismatch then do 16-bit subtract.

define i8 @cmp_slt_i16(i16 %a, i16 %b) {
; CHECK-LABEL: cmp_slt_i16:
; CHECK:       LBB2_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, H
; CHECK-NEXT:    MOV E, L
; CHECK-NEXT:    MOV H, D
; CHECK-NEXT:    MOV L, E
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRA B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB2_3
; CHECK-NEXT:  LBB2_1:
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV C, E
; CHECK-NEXT:    JC LBB2_4
; CHECK-NEXT:  LBB2_2:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    JMP LBB2_5
; CHECK-NEXT:  LBB2_3:
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB2_2
; CHECK-NEXT:  LBB2_4:
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:  LBB2_5:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    POP D
; CHECK:    RET

  %cmp = icmp slt i16 %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}

; Unsigned i16 greater-or-equal should use carry from 16-bit subtract.

define i8 @cmp_uge_i16(i16 %a, i16 %b) {
; CHECK-LABEL: cmp_uge_i16:
; CHECK:       LBB3_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, H
; CHECK-NEXT:    MOV E, L
; CHECK-NEXT:    MOV H, D
; CHECK-NEXT:    MOV L, E
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV C, E
; CHECK-NEXT:    JNC LBB3_2
; CHECK-NEXT:  LBB3_1:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    JMP LBB3_3
; CHECK-NEXT:  LBB3_2:
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:  LBB3_3:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    POP D
; CHECK:    RET

  %cmp = icmp uge i16 %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}

; Unsigned i8 greater-or-equal should use carry from subtract.

define i8 @cmp_uge_i8(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_uge_i8:
; CHECK:       LBB4_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, H
; CHECK-NEXT:    MOV E, L
; CHECK-NEXT:    LDAX D
; CHECK-NEXT:    SUB B
; CHECK-NEXT:    JNC LBB4_2
; CHECK-NEXT:  LBB4_1:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    JMP LBB4_3
; CHECK-NEXT:  LBB4_2:
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:  LBB4_3:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    POP D
; CHECK:    RET

  %cmp = icmp uge i8 %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}
