; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; i8 equality select

define i8 @cmp_eq_i8(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_eq_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    SUB B
; CHECK-NEXT:    JZ LBB0_1
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_1:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET

  %cmp = icmp eq i8 %a, %b
  %sel = select i1 %cmp, i8 1, i8 0
  ret i8 %sel
}

; i8 unsigned less-than select

define i8 @cmp_ult_i8(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_ult_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    SUB B
; CHECK-NEXT:    JC LBB1_1
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB1_1:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET

  %cmp = icmp ult i8 %a, %b
  %sel = select i1 %cmp, i8 1, i8 0
  ret i8 %sel
}

; i16 equality select

define i8 @cmp_eq_i16(i16 %a, i16 %b) {
; CHECK-LABEL: cmp_eq_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV H, M
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    CMP D
; CHECK-NEXT:    JNZ LBB2_3
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    CMP E
; CHECK-NEXT:    JNZ LBB2_3
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:  ; %bb.4:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB2_3:
; CHECK-NEXT:  ; %bb.5:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    RET

  %cmp = icmp eq i16 %a, %b
  %sel = select i1 %cmp, i8 1, i8 0
  ret i8 %sel
}

; i16 unsigned less-than select

define i8 @cmp_ult_i16(i16 %a, i16 %b) {
; CHECK-LABEL: cmp_ult_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    JNC LBB3_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB3_2:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET

  %cmp = icmp ult i16 %a, %b
  %sel = select i1 %cmp, i8 1, i8 0
  ret i8 %sel
}
