# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -O0 -run-pass=i8085-expand-pseudo32 %s -o - | FileCheck %s

--- |
  target triple = "i8085-unknown-elf"
  define void @mvi32_iax() { ret void }
  define void @add32_iax_ibx() { ret void }
  define void @sub32_iax_ibx() { ret void }
...

---
name:            mvi32_iax
body:             |
  bb.0:
    ; CHECK-LABEL: name: mvi32_iax
    ; CHECK: $iax = IMPLICIT_DEF
    ; CHECK-NEXT: $hl = LXI 0
    ; CHECK-NEXT: DAD $sp, implicit-def $sreg, implicit-def $h, implicit-def $l, implicit $h, implicit $l
    ; CHECK-NEXT: MVI_M 4, implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: MVI_M 3, implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: MVI_M 2, implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: MVI_M 1, implicit $h, implicit $l
    ; CHECK-NEXT: RET implicit $sp, implicit-def $sp
    $iax = MVI_32 16909060, implicit-def $a, implicit-def $hl
    RET implicit $sp, implicit-def $sp
...

---
name:            add32_iax_ibx
body:             |
  bb.0:
    liveins: $iax, $ibx
    ; CHECK-LABEL: name: add32_iax_ibx
    ; CHECK: liveins: $iax, $ibx
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $iax = IMPLICIT_DEF
    ; CHECK-NEXT: $ibx = IMPLICIT_DEF
    ; CHECK-NEXT: $hl = LXI 0
    ; CHECK-NEXT: DAD $sp, implicit-def $sreg, implicit-def $h, implicit-def $l, implicit $h, implicit $l
    ; CHECK-NEXT: $a = MOV_FROM_M implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: ADD_M implicit-def $sreg, implicit-def $a, implicit $h, implicit $l, implicit $a
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: MOV_M $a, implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $a = MOV_FROM_M implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: ADC_M implicit-def $sreg, implicit-def $a, implicit $h, implicit $l, implicit $a, implicit $sreg
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: MOV_M $a, implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $a = MOV_FROM_M implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: ADC_M implicit-def $sreg, implicit-def $a, implicit $h, implicit $l, implicit $a, implicit $sreg
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: MOV_M $a, implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $a = MOV_FROM_M implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: ADC_M implicit-def $sreg, implicit-def $a, implicit $h, implicit $l, implicit $a, implicit $sreg
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: MOV_M $a, implicit $h, implicit $l
    ; CHECK-NEXT: RET implicit $sp, implicit-def $sp
    $iax = ADD_32 $iax, $ibx, implicit-def $sreg, implicit-def $a, implicit-def $hl
    RET implicit $sp, implicit-def $sp
...

---
name:            sub32_iax_ibx
body:             |
  bb.0:
    liveins: $iax, $ibx
    ; CHECK-LABEL: name: sub32_iax_ibx
    ; CHECK: liveins: $iax, $ibx
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $iax = IMPLICIT_DEF
    ; CHECK-NEXT: $ibx = IMPLICIT_DEF
    ; CHECK-NEXT: $hl = LXI 0
    ; CHECK-NEXT: DAD $sp, implicit-def $sreg, implicit-def $h, implicit-def $l, implicit $h, implicit $l
    ; CHECK-NEXT: $a = MOV_FROM_M implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: SUB_M implicit-def $sreg, implicit-def $a, implicit $h, implicit $l, implicit $a
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: MOV_M $a, implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $a = MOV_FROM_M implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: SBB_M implicit-def $sreg, implicit-def $a, implicit $h, implicit $l, implicit $a, implicit $sreg
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: MOV_M $a, implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $a = MOV_FROM_M implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: SBB_M implicit-def $sreg, implicit-def $a, implicit $h, implicit $l, implicit $a, implicit $sreg
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: MOV_M $a, implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $a = MOV_FROM_M implicit $h, implicit $l
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: $hl = INX
    ; CHECK-NEXT: SBB_M implicit-def $sreg, implicit-def $a, implicit $h, implicit $l, implicit $a, implicit $sreg
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: $hl = DCX
    ; CHECK-NEXT: MOV_M $a, implicit $h, implicit $l
    ; CHECK-NEXT: RET implicit $sp, implicit-def $sp
    $iax = SUB_32 $iax, $ibx, implicit-def $sreg, implicit-def $a, implicit-def $hl
    RET implicit $sp, implicit-def $sp
...
