; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

define i16 @zext_i8(i8 %a) {
; CHECK-LABEL: zext_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    RET
  %z = zext i8 %a to i16
  ret i16 %z
}

define i16 @sext_i8(i8 %a) {
; CHECK-LABEL: sext_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    ADI 128
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET
  %s = sext i8 %a to i16
  ret i16 %s
}

define i8 @trunc_i16(i16 %a) {
; CHECK-LABEL: trunc_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    RET
  %t = trunc i16 %a to i8
  ret i8 %t
}
