; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

define float @fadd_f32(float %a, float %b) {
; CHECK-LABEL: fadd_f32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65524
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 12
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __addsf3
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967284
; CHECK-NEXT:    RET
  %r = fadd float %a, %b
  ret float %r
}

define float @fsub_f32(float %a, float %b) {
; CHECK-LABEL: fsub_f32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65524
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 12
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __subsf3
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967284
; CHECK-NEXT:    RET
  %r = fsub float %a, %b
  ret float %r
}

define float @fmul_f32(float %a, float %b) {
; CHECK-LABEL: fmul_f32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65524
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 12
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __mulsf3
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967284
; CHECK-NEXT:    RET
  %r = fmul float %a, %b
  ret float %r
}

define float @fdiv_f32(float %a, float %b) {
; CHECK-LABEL: fdiv_f32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65524
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 12
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __divsf3
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967284
; CHECK-NEXT:    RET
  %r = fdiv float %a, %b
  ret float %r
}

define i1 @fcmp_eq_f32(float %a, float %b) {
; CHECK-LABEL: fcmp_eq_f32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    ; implicit-def: $ibx
; CHECK-NEXT:    LXI H, 65520
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 16
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __eqsf2
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB4_6
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    LXI H, 13
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB4_6
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB4_6
; CHECK-NEXT:  ; %bb.3:
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB4_6
; CHECK-NEXT:  ; %bb.4:
; CHECK-NEXT:    JMP LBB4_5
; CHECK-NEXT:  LBB4_6:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:  LBB4_5:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967280
; CHECK-NEXT:    RET
  %r = fcmp oeq float %a, %b
  ret i1 %r
}

define i1 @fcmp_lt_f32(float %a, float %b) {
; CHECK-LABEL: fcmp_lt_f32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    ; implicit-def: $ibx
; CHECK-NEXT:    LXI H, 65520
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 16
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __ltsf2
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB5_6
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_8
; CHECK-NEXT:    JNZ LBB5_11
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_8
; CHECK-NEXT:    JNZ LBB5_11
; CHECK-NEXT:  ; %bb.3:
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 13
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_8
; CHECK-NEXT:    JNZ LBB5_11
; CHECK-NEXT:  ; %bb.4:
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 12
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_8
; CHECK-NEXT:    JNZ LBB5_11
; CHECK-NEXT:  LBB5_11:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    JMP LBB5_9
; CHECK-NEXT:  LBB5_6:
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB5_11
; CHECK-NEXT:  LBB5_8:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:  LBB5_9:
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967280
; CHECK-NEXT:    RET
  %r = fcmp olt float %a, %b
  ret i1 %r
}

define i1 @fcmp_gt_f32(float %a, float %b) {
; CHECK-LABEL: fcmp_gt_f32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    ; implicit-def: $ibx
; CHECK-NEXT:    LXI H, 65520
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 16
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __gtsf2
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB6_6
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB6_7
; CHECK-NEXT:    JNZ LBB6_11
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB6_7
; CHECK-NEXT:    JNZ LBB6_11
; CHECK-NEXT:  ; %bb.3:
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB6_7
; CHECK-NEXT:    JNZ LBB6_11
; CHECK-NEXT:  ; %bb.4:
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB6_7
; CHECK-NEXT:    JNZ LBB6_11
; CHECK-NEXT:  LBB6_11:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    JMP LBB6_8
; CHECK-NEXT:  LBB6_6:
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB6_11
; CHECK-NEXT:  LBB6_7:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:  LBB6_8:
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967280
; CHECK-NEXT:    RET
  %r = fcmp ogt float %a, %b
  ret i1 %r
}

define float @sitofp_i32(i32 %a) {
; CHECK-LABEL: sitofp_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65528
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 8
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __floatsisf
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967288
; CHECK-NEXT:    RET
  %r = sitofp i32 %a to float
  ret float %r
}

define float @uitofp_i32(i32 %a) {
; CHECK-LABEL: uitofp_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65528
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 8
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __floatunsisf
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967288
; CHECK-NEXT:    RET
  %r = uitofp i32 %a to float
  ret float %r
}

define i32 @fptosi_i32(float %a) {
; CHECK-LABEL: fptosi_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65528
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 8
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __fixsfsi
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967288
; CHECK-NEXT:    RET
  %r = fptosi float %a to i32
  ret i32 %r
}

define i32 @fptoui_i32(float %a) {
; CHECK-LABEL: fptoui_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65528
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 8
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __fixunssfsi
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967288
; CHECK-NEXT:    RET
  %r = fptoui float %a to i32
  ret i32 %r
}
