; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --function load_globals --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

@g8 = global i8 0
@g16 = global i16 0

; Global addressing should lower via absolute address materialization.

define void @store_globals(i8 %a, i16 %b) {
; CHECK-LABEL: store_globals:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, g8
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, g16
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    RET
entry:
  store i8 %a, i8* @g8, align 1
  store i16 %b, i16* @g16, align 1
  ret void
}

define i16 @load_globals() {
; CHECK-LABEL: load_globals:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, g8
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    LXI H, g16+1
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    LXI H, g16
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ADD E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADC D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET
entry:
  %a = load i8, i8* @g8, align 1
  %b = load i16, i16* @g16, align 1
  %a16 = zext i8 %a to i16
  %sum = add i16 %a16, %b
  ret i16 %sum
}
