; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

define i64 @mul64(i64 %a, i64 %b) {
; CHECK-LABEL: mul64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65506
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 30
; CHECK-NEXT:    LXI H, 46
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 42
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 38
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 34
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __muldi3
; CHECK-NEXT:    LXI H, 32
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 27
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 28
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 29
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 23
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 24
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 25
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967266
; CHECK-NEXT:    RET
entry:
  %r = mul i64 %a, %b
  ret i64 %r
}

define i64 @sdiv64(i64 %a, i64 %b) {
; CHECK-LABEL: sdiv64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65506
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 30
; CHECK-NEXT:    LXI H, 46
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 42
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 38
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 34
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __divdi3
; CHECK-NEXT:    LXI H, 32
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 27
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 28
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 29
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 23
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 24
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 25
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967266
; CHECK-NEXT:    RET
entry:
  %r = sdiv i64 %a, %b
  ret i64 %r
}

define i64 @udiv64(i64 %a, i64 %b) {
; CHECK-LABEL: udiv64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65506
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 30
; CHECK-NEXT:    LXI H, 46
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 42
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 38
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 34
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __udivdi3
; CHECK-NEXT:    LXI H, 32
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 27
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 28
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 29
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 23
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 24
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 25
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967266
; CHECK-NEXT:    RET
entry:
  %r = udiv i64 %a, %b
  ret i64 %r
}

define i64 @srem64(i64 %a, i64 %b) {
; CHECK-LABEL: srem64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65506
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 30
; CHECK-NEXT:    LXI H, 46
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 42
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 38
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 34
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __moddi3
; CHECK-NEXT:    LXI H, 32
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 27
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 28
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 29
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 23
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 24
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 25
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967266
; CHECK-NEXT:    RET
entry:
  %r = srem i64 %a, %b
  ret i64 %r
}

define i64 @urem64(i64 %a, i64 %b) {
; CHECK-LABEL: urem64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65506
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 30
; CHECK-NEXT:    LXI H, 46
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 42
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 38
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 34
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __umoddi3
; CHECK-NEXT:    LXI H, 32
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 27
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 28
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 29
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 23
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 24
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 25
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967266
; CHECK-NEXT:    RET
entry:
  %r = urem i64 %a, %b
  ret i64 %r
}

define i64 @shl64(i64 %a, i8 %b) {
; CHECK-LABEL: shl64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65510
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 26
; CHECK-NEXT:    LXI H, 34
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 38
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __ashldi3
; CHECK-NEXT:    LXI H, 28
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 23
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 24
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 25
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967270
; CHECK-NEXT:    RET
entry:
  %bb = zext i8 %b to i64
  %r = shl i64 %a, %bb
  ret i64 %r
}

define i64 @lshr64(i64 %a, i8 %b) {
; CHECK-LABEL: lshr64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65510
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 26
; CHECK-NEXT:    LXI H, 34
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 38
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __lshrdi3
; CHECK-NEXT:    LXI H, 28
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 23
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 24
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 25
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967270
; CHECK-NEXT:    RET
entry:
  %bb = zext i8 %b to i64
  %r = lshr i64 %a, %bb
  ret i64 %r
}

define i64 @ashr64(i64 %a, i8 %b) {
; CHECK-LABEL: ashr64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65510
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 26
; CHECK-NEXT:    LXI H, 34
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 38
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __ashrdi3
; CHECK-NEXT:    LXI H, 28
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 23
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 24
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 25
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967270
; CHECK-NEXT:    RET
entry:
  %bb = zext i8 %b to i64
  %r = ashr i64 %a, %bb
  ret i64 %r
}

declare i64 @llvm.ctlz.i64(i64, i1)

define i64 @clz64(i64 %a) {
; CHECK-LABEL: clz64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65522
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 14
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 12
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __clzdi2
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967282
; CHECK-NEXT:    RET
entry:
  %r = call i64 @llvm.ctlz.i64(i64 %a, i1 false)
  ret i64 %r
}
