; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Extra branch coverage for i32/i64 compares.

define i8 @br_eq_i32(i32 %a, i32 %b) {
; CHECK-LABEL: br_eq_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    ; implicit-def: $ibx
; CHECK-NEXT:    LXI H, 65528
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 8
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB0_6
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB0_6
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB0_6
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB0_6
; CHECK-NEXT:  ; %bb.5: ; %entry
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:  LBB0_6: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB0_9
; CHECK-NEXT:  ; %bb.7: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    JMP LBB0_8
; CHECK-NEXT:  LBB0_9: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:  LBB0_8: ; %t
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967288
; CHECK-NEXT:    RET
entry:
  %cmp = icmp eq i32 %a, %b
  br i1 %cmp, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}

define i8 @br_ult_i32(i32 %a, i32 %b) {
; CHECK-LABEL: br_ult_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    ; implicit-def: $ibx
; CHECK-NEXT:    LXI H, 65528
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 8
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB1_5
; CHECK-NEXT:    JNZ LBB1_8
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB1_5
; CHECK-NEXT:    JNZ LBB1_8
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB1_5
; CHECK-NEXT:    JNZ LBB1_8
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB1_5
; CHECK-NEXT:    JNZ LBB1_8
; CHECK-NEXT:    JMP LBB1_8
; CHECK-NEXT:  LBB1_5: ; %entry
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JZ LBB1_9
; CHECK-NEXT:  LBB1_6: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    JMP LBB1_10
; CHECK-NEXT:  LBB1_8: ; %entry
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB1_6
; CHECK-NEXT:  LBB1_9: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:  LBB1_10: ; %t
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967288
; CHECK-NEXT:    RET
entry:
  %cmp = icmp ult i32 %a, %b
  br i1 %cmp, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}

define i8 @br_slt_i32(i32 %a, i32 %b) {
; CHECK-LABEL: br_slt_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    ; implicit-def: $ibx
; CHECK-NEXT:    LXI H, 65528
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 8
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB2_8
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB2_6
; CHECK-NEXT:    JNZ LBB2_11
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB2_6
; CHECK-NEXT:    JNZ LBB2_11
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB2_6
; CHECK-NEXT:    JNZ LBB2_11
; CHECK-NEXT:  ; %bb.4: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB2_6
; CHECK-NEXT:    JNZ LBB2_11
; CHECK-NEXT:  LBB2_11: ; %entry
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB2_7
; CHECK-NEXT:  LBB2_12: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    JMP LBB2_13
; CHECK-NEXT:  LBB2_8: ; %entry
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB2_11
; CHECK-NEXT:  LBB2_6: ; %entry
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JZ LBB2_12
; CHECK-NEXT:  LBB2_7: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:  LBB2_13: ; %t
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967288
; CHECK-NEXT:    RET
entry:
  %cmp = icmp slt i32 %a, %b
  br i1 %cmp, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}

define i8 @br_eq_i64(i64 %a, i64 %b) {
; CHECK-LABEL: br_eq_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    ; implicit-def: $ibx
; CHECK-NEXT:    LXI H, 65520
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 16
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    POP H
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    POP H
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    POP H
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    POP H
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORA M
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ORA M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ORA M
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    ORA M
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB3_6
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB3_6
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB3_6
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB3_6
; CHECK-NEXT:  ; %bb.5: ; %entry
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:  LBB3_6: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB3_9
; CHECK-NEXT:  ; %bb.7: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    JMP LBB3_8
; CHECK-NEXT:  LBB3_9: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:  LBB3_8: ; %t
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967280
; CHECK-NEXT:    RET
entry:
  %cmp = icmp eq i64 %a, %b
  br i1 %cmp, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}

define i8 @br_ult_i64(i64 %a, i64 %b) {
; CHECK-LABEL: br_ult_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    ; implicit-def: $ibx
; CHECK-NEXT:    LXI H, 65520
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 16
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    POP H
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    POP H
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB4_5
; CHECK-NEXT:    JNZ LBB4_7
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB4_5
; CHECK-NEXT:    JNZ LBB4_7
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB4_5
; CHECK-NEXT:    JNZ LBB4_7
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB4_5
; CHECK-NEXT:    JNZ LBB4_7
; CHECK-NEXT:    JMP LBB4_7
; CHECK-NEXT:  LBB4_5: ; %entry
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    JMP LBB4_8
; CHECK-NEXT:  LBB4_7: ; %entry
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:  LBB4_8: ; %entry
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 27
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 28
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 29
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB4_13
; CHECK-NEXT:    JNZ LBB4_15
; CHECK-NEXT:  ; %bb.9: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB4_13
; CHECK-NEXT:    JNZ LBB4_15
; CHECK-NEXT:  ; %bb.10: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB4_13
; CHECK-NEXT:    JNZ LBB4_15
; CHECK-NEXT:  ; %bb.11: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB4_13
; CHECK-NEXT:    JNZ LBB4_15
; CHECK-NEXT:    JMP LBB4_15
; CHECK-NEXT:  LBB4_13: ; %entry
; CHECK-NEXT:    MVI C, 0
; CHECK-NEXT:    JMP LBB4_16
; CHECK-NEXT:  LBB4_15: ; %entry
; CHECK-NEXT:    MVI C, 1
; CHECK-NEXT:  LBB4_16: ; %entry
; CHECK-NEXT:    MVI D, 1
; CHECK-NEXT:    LXI H, 12
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 13
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 12
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 13
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    POP H
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB4_21
; CHECK-NEXT:  ; %bb.17: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB4_21
; CHECK-NEXT:  ; %bb.18: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB4_21
; CHECK-NEXT:  ; %bb.19: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JZ LBB4_22
; CHECK-NEXT:  LBB4_21: ; %entry
; CHECK-NEXT:    MVI D, 0
; CHECK-NEXT:  LBB4_22: ; %entry
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB4_24
; CHECK-NEXT:  ; %bb.23: ; %entry
; CHECK-NEXT:    MOV C, B
; CHECK-NEXT:  LBB4_24: ; %entry
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB4_25
; CHECK-NEXT:  ; %bb.27: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    JMP LBB4_28
; CHECK-NEXT:  LBB4_25: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:  LBB4_28: ; %t
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967280
; CHECK-NEXT:    RET
entry:
  %cmp = icmp ult i64 %a, %b
  br i1 %cmp, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}

define i8 @br_slt_i64(i64 %a, i64 %b) {
; CHECK-LABEL: br_slt_i64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    ; implicit-def: $ibx
; CHECK-NEXT:    LXI H, 65520
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 16
; CHECK-NEXT:    LXI H, 30
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    LXI H, 22
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 17
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    POP H
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 12
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 13
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    POP H
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    XRA M
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB5_6
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_7
; CHECK-NEXT:    JNZ LBB5_10
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_7
; CHECK-NEXT:    JNZ LBB5_10
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_7
; CHECK-NEXT:    JNZ LBB5_10
; CHECK-NEXT:  ; %bb.4: ; %entry
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_7
; CHECK-NEXT:    JNZ LBB5_10
; CHECK-NEXT:    JMP LBB5_10
; CHECK-NEXT:  LBB5_6: ; %entry
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB5_10
; CHECK-NEXT:  LBB5_7: ; %entry
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:  LBB5_10: ; %entry
; CHECK-NEXT:    LXI H, 26
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 27
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 28
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 29
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 18
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 19
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 20
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 21
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_15
; CHECK-NEXT:    JNZ LBB5_17
; CHECK-NEXT:  ; %bb.11: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_15
; CHECK-NEXT:    JNZ LBB5_17
; CHECK-NEXT:  ; %bb.12: ; %entry
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_15
; CHECK-NEXT:    JNZ LBB5_17
; CHECK-NEXT:  ; %bb.13: ; %entry
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JC LBB5_15
; CHECK-NEXT:    JNZ LBB5_17
; CHECK-NEXT:    JMP LBB5_17
; CHECK-NEXT:  LBB5_15: ; %entry
; CHECK-NEXT:    MVI C, 0
; CHECK-NEXT:    JMP LBB5_18
; CHECK-NEXT:  LBB5_17: ; %entry
; CHECK-NEXT:    MVI C, 1
; CHECK-NEXT:  LBB5_18: ; %entry
; CHECK-NEXT:    MVI D, 1
; CHECK-NEXT:    LXI H, 12
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 13
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 14
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 15
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 11
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 12
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 13
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    POP H
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB5_23
; CHECK-NEXT:  ; %bb.19: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB5_23
; CHECK-NEXT:  ; %bb.20: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JNZ LBB5_23
; CHECK-NEXT:  ; %bb.21: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    CMP M
; CHECK-NEXT:    JZ LBB5_24
; CHECK-NEXT:  LBB5_23: ; %entry
; CHECK-NEXT:    MVI D, 0
; CHECK-NEXT:  LBB5_24: ; %entry
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB5_26
; CHECK-NEXT:  ; %bb.25: ; %entry
; CHECK-NEXT:    MOV C, B
; CHECK-NEXT:  LBB5_26: ; %entry
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB5_27
; CHECK-NEXT:  ; %bb.29: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    JMP LBB5_30
; CHECK-NEXT:  LBB5_27: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:  LBB5_30: ; %t
; CHECK-NEXT:    LXI H, 16
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967280
; CHECK-NEXT:    RET
entry:
  %cmp = icmp slt i64 %a, %b
  br i1 %cmp, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}
