; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085  -verify-machineinstrs  | FileCheck %s

define i16 @loadtest16() #0  {
; CHECK-LABEL: loadtest16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 65532
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:    LXI B, 20000
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    LXI D, 105
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967292
; CHECK-NEXT:    RET

  %1 = alloca i16, align 1
  store i16 105, i16* %1, align 1
  %2 = load i16, i16* %1, align 1

  %3 = alloca i16, align 1
  store i16 20000, i16* %3, align 1
  %4 = load i16, i16* %3, align 1
  ret i16 %4

}


define i8 @loadtest8()  {
; CHECK-LABEL: loadtest8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 65534
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK-NEXT:    MVI A, 111
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    MVI B, 55
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967294
; CHECK-NEXT:    RET

  %1 = alloca i8, align 1
  store i8 55, i8* %1, align 1
  %2 = load i8, i8* %1, align 1

  %3 = alloca i8, align 1
  store i8 111, i8* %3, align 1
  %4 = load i8, i8* %3, align 1
  ret i8 %4
}
