; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs  | FileCheck %s

define i8 @functionone(i8,i8) {
; CHECK-LABEL: functionone:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA C
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    ANA C
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    ORA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET

  %3 = xor i8 %0, %1
  %4 = and i8 %3, %1
  %5 = or i8 %4, %0
  ret i8 %5
}

define i16 @functiontwo(i16,i16) {
; CHECK-LABEL: functiontwo:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV H, M
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ANA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ORA L
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORA H
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET

  %3 = xor i16 %0, %1
  %4 = and i16 %3, %1
  %5 = or i16 %4, %0
  ret i16 %5
}

define i8 @functionthree(i8,i8) {
; CHECK-LABEL: functionthree:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    XRA B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    ANI 40
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    ORI 80
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    XRI 111
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET

  %3 = xor i8 %0, %1
  %4 = and i8 %3, 40
  %5 = or i8 %4, 80
  %6 = xor i8 %5, 111
  ret i8 %6
}

define i16 @functionfour(i16,i16) {
; CHECK-LABEL: functionfour:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI D, -29632
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ANA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI D, 12345
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ORA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI D, -10858
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET

  %3 = xor i16 %0, %1
  %4 = and i16 %3, 40000
  %5 = or i16 %4, 12345
  %6 = xor i16 %5, 54678
  ret i16 %6
}
