; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs  | FileCheck %s

define i8 @functionone(i8,i8) {
; CHECK-LABEL: functionone:
; CHECK:       LBB0_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, H
; CHECK-NEXT:    MOV E, L
; CHECK-NEXT:    LDAX D
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV D, C
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRA B
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ANA B
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ORA C
; CHECK-NEXT:    POP D
; CHECK:    RET

  %3 = xor i8 %0, %1
  %4 = and i8 %3, %1
  %5 = or i8 %4, %0
  ret i8 %5
}

define i16 @functiontwo(i16,i16) {
; CHECK-LABEL: functiontwo:
; CHECK:       LBB1_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK:    LXI H, 65534
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset {{[0-9]+}}
; CHECK:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    INX B
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    DCX B
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV C, E
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV H, M
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA L
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA H
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ANA L
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANA H
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ORA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORA D
; CHECK-NEXT:    MOV B, A
; CHECK:    POP D
; CHECK:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset {{[0-9]+}}
; CHECK:    RET

  %3 = xor i16 %0, %1
  %4 = and i16 %3, %1
  %5 = or i16 %4, %0
  ret i16 %5
}

define i8 @functionthree(i8,i8) {
; CHECK-LABEL: functionthree:
; CHECK:       LBB2_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, H
; CHECK-NEXT:    MOV E, L
; CHECK-NEXT:    LDAX D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA C
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANI 40
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORI 80
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRI 111
; CHECK-NEXT:    POP D
; CHECK:    RET

  %3 = xor i8 %0, %1
  %4 = and i8 %3, 40
  %5 = or i8 %4, 80
  %6 = xor i8 %5, 111
  ret i8 %6
}

define i16 @functionfour(i16,i16) {
; CHECK-LABEL: functionfour:
; CHECK:       LBB3_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    INX B
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    DCX B
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI H, -29632
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ANA L
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANA H
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI H, 12345
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ORA L
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORA H
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI H, -10858
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA L
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA H
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    POP D
; CHECK:    RET

  %3 = xor i16 %0, %1
  %4 = and i16 %3, 40000
  %5 = or i16 %4, 12345
  %6 = xor i16 %5, 54678
  ret i16 %6
}
