; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --function stack_global_mix --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Large stack offsets and mixed-width loads/stores.

define i8 @stack_large_i8() {
; CHECK-LABEL: stack_large_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 65024
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 512
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MVI A, 42
; CHECK-NEXT:    LXI H, 300
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 512
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294966784
; CHECK-NEXT:    RET
entry:
  %buf = alloca [512 x i8], align 1
  %p = getelementptr [512 x i8], ptr %buf, i16 0, i16 300
  store i8 42, ptr %p, align 1
  %v = load i8, ptr %p, align 1
  ret i8 %v
}

define i16 @stack_large_i16() {
; CHECK-LABEL: stack_large_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 65024
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 512
; CHECK-NEXT:    LXI B, 4097
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, H
; CHECK-NEXT:    MOV E, L
; CHECK-NEXT:    LXI H, 240
; CHECK-NEXT:    DAD D
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    LXI H, 512
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294966784
; CHECK-NEXT:    RET
entry:
  %buf = alloca [256 x i16], align 1
  %p = getelementptr [256 x i16], ptr %buf, i16 0, i16 120
  store i16 4097, ptr %p, align 1
  %v = load i16, ptr %p, align 1
  ret i16 %v
}

; Mix global + large stack offset.
@glob = global i8 0

define i8 @stack_global_mix(i8 %x) {
; CHECK-LABEL: stack_global_mix:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 65136
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 400
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LXI H, 402
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 255
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, glob
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 400
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294966896
; CHECK-NEXT:    RET
entry:
  %buf = alloca [400 x i8], align 1
  %p = getelementptr [400 x i8], ptr %buf, i16 0, i16 255
  store i8 %x, ptr %p, align 1
  %v = load i8, ptr %p, align 1
  store i8 %v, ptr @glob, align 1
  ret i8 %v
}
