; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

declare { i16, i1 } @llvm.umul.with.overflow.i16(i16, i16)
declare { i8, i1 } @llvm.smul.with.overflow.i8(i8, i8)

define i16 @umul_ov_i16(i16 %a, i16 %b) {
; CHECK-LABEL: umul_ov_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65528
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 8
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __mului16
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967288
; CHECK-NEXT:    RET
entry:
  %res = call { i16, i1 } @llvm.umul.with.overflow.i16(i16 %a, i16 %b)
  %sum = extractvalue { i16, i1 } %res, 0
  ret i16 %sum
}

define i1 @umul_ov_flag(i16 %a, i16 %b) {
; CHECK-LABEL: umul_ov_flag:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65528
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 8
; CHECK-NEXT:    LXI H, 10
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    CALL __mului16
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    CMP H
; CHECK-NEXT:    JNZ LBB1_3
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    CMP L
; CHECK-NEXT:    JNZ LBB1_3
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:  ; %bb.4: ; %entry
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    JMP LBB1_5
; CHECK-NEXT:  LBB1_3: ; %entry
; CHECK-NEXT:  LBB1_5: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967288
; CHECK-NEXT:    RET
entry:
  %res = call { i16, i1 } @llvm.umul.with.overflow.i16(i16 %a, i16 %b)
  %ov = extractvalue { i16, i1 } %res, 1
  ret i1 %ov
}

define i8 @smul_ov_i8(i8 %a, i8 %b) {
; CHECK-LABEL: smul_ov_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 65534
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __mulsi8
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967294
; CHECK-NEXT:    RET
entry:
  %res = call { i8, i1 } @llvm.smul.with.overflow.i8(i8 %a, i8 %b)
  %sum = extractvalue { i8, i1 } %res, 0
  ret i8 %sum
}

define i1 @smul_ov_flag(i8 %a, i8 %b) {
; CHECK-LABEL: smul_ov_flag:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 65534
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 2
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __mulsi8
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    ADI 128
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MVI D, 1
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CMP H
; CHECK-NEXT:    JNZ LBB3_3
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    CMP L
; CHECK-NEXT:    JNZ LBB3_3
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:  ; %bb.4: ; %entry
; CHECK-NEXT:    MVI D, 0
; CHECK-NEXT:    JMP LBB3_5
; CHECK-NEXT:  LBB3_3: ; %entry
; CHECK-NEXT:  LBB3_5: ; %entry
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967294
; CHECK-NEXT:    RET
entry:
  %res = call { i8, i1 } @llvm.smul.with.overflow.i8(i8 %a, i8 %b)
  %ov = extractvalue { i8, i1 } %res, 1
  ret i1 %ov
}
