; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Overflow intrinsics used in branch contexts.

declare { i16, i1 } @llvm.uadd.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.sadd.with.overflow.i16(i16, i16)
declare { i8, i1 } @llvm.usub.with.overflow.i8(i8, i8)

define i8 @br_uadd_ov(i16 %a, i16 %b) {
; CHECK-LABEL: br_uadd_ov:
; CHECK:       LBB0_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, H
; CHECK-NEXT:    MOV E, L
; CHECK-NEXT:    MOV H, D
; CHECK-NEXT:    MOV L, E
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV H, D
; CHECK-NEXT:    MOV L, E
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    ADD C
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ADC B
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SBB D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    JNC LBB0_2
; CHECK-NEXT:  LBB0_1:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    JMP LBB0_3
; CHECK-NEXT:  LBB0_2:
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:  LBB0_3:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORI 0
; CHECK-NEXT:    JNZ LBB0_5
; CHECK-NEXT:  LBB0_4:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    POP D
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_5:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    POP D
; CHECK-NEXT:    RET
entry:
  %res = call { i16, i1 } @llvm.uadd.with.overflow.i16(i16 %a, i16 %b)
  %ov = extractvalue { i16, i1 } %res, 1
  br i1 %ov, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}

define i8 @br_sadd_ov(i16 %a, i16 %b) {
; CHECK-LABEL: br_sadd_ov:
; CHECK:       LBB1_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    LXI H, 65533
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    LXI H, 9
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    LXI B, 0
; CHECK-NEXT:    MVI D, 1
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRA B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB1_6
; CHECK-NEXT:  LBB1_1:
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV C, E
; CHECK-NEXT:    JC LBB1_3
; CHECK-NEXT:  LBB1_2:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:  LBB1_3:
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    ADD E
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ADC D
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    XRA B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB1_7
; CHECK-NEXT:  LBB1_4:
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    JC LBB1_8
; CHECK-NEXT:  LBB1_5:
; CHECK-NEXT:    MVI C, 0
; CHECK-NEXT:    JMP LBB1_9
; CHECK-NEXT:  LBB1_6:
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB1_3
; CHECK-NEXT:    JMP LBB1_2
; CHECK-NEXT:  LBB1_7:
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB1_5
; CHECK-NEXT:  LBB1_8:
; CHECK-NEXT:    MVI C, 1
; CHECK-NEXT:  LBB1_9:
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    JZ LBB1_11
; CHECK-NEXT:  LBB1_10:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    JMP LBB1_12
; CHECK-NEXT:  LBB1_11:
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:  LBB1_12:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORI 0
; CHECK-NEXT:    JNZ LBB1_14
; CHECK-NEXT:  LBB1_13:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    JMP LBB1_15
; CHECK-NEXT:  LBB1_14:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:  LBB1_15:
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    POP D
; CHECK-NEXT:    RET
entry:
  %res = call { i16, i1 } @llvm.sadd.with.overflow.i16(i16 %a, i16 %b)
  %ov = extractvalue { i16, i1 } %res, 1
  br i1 %ov, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}

define i8 @br_usub_ov(i8 %a, i8 %b) {
; CHECK-LABEL: br_usub_ov:
; CHECK:       LBB2_0:
; CHECK-NEXT:    PUSH D
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, H
; CHECK-NEXT:    MOV E, L
; CHECK-NEXT:    LDAX D
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV D, C
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SUB B
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    JZ LBB2_2
; CHECK-NEXT:    JC LBB2_2
; CHECK-NEXT:  LBB2_1:
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:  LBB2_2:
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORI 0
; CHECK-NEXT:    JNZ LBB2_4
; CHECK-NEXT:  LBB2_3:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    POP D
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB2_4:
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    POP D
; CHECK-NEXT:    RET
entry:
  %res = call { i8, i1 } @llvm.usub.with.overflow.i8(i8 %a, i8 %b)
  %ov = extractvalue { i8, i1 } %res, 1
  br i1 %ov, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}
