; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Overflow intrinsics used in branch contexts.

declare { i16, i1 } @llvm.uadd.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.sadd.with.overflow.i16(i16, i16)
declare { i8, i1 } @llvm.usub.with.overflow.i8(i8, i8)

define i8 @br_uadd_ov(i16 %a, i16 %b) {
; CHECK-LABEL: br_uadd_ov:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV H, D
; CHECK-NEXT:    MOV L, E
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    ADD C
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ADC B
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SBB D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    JNC LBB0_1
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB0_4
; CHECK-NEXT:  LBB0_3: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_1: ; %entry
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JZ LBB0_3
; CHECK-NEXT:  LBB0_4: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
entry:
  %res = call { i16, i1 } @llvm.uadd.with.overflow.i16(i16 %a, i16 %b)
  %ov = extractvalue { i16, i1 } %res, 1
  br i1 %ov, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}

define i8 @br_sadd_ov(i16 %a, i16 %b) {
; CHECK-LABEL: br_sadd_ov:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    ADD E
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ADC D
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    XRA L
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRA H
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    XRA L
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA H
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ANA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI D, -1
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA D
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB1_4
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    SBB D
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    JC LBB1_2
; CHECK-NEXT:  ; %bb.6: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CMP D
; CHECK-NEXT:    JNZ LBB1_12
; CHECK-NEXT:  ; %bb.7: ; %entry
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    CMP E
; CHECK-NEXT:    JZ LBB1_2
; CHECK-NEXT:  LBB1_12: ; %entry
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JZ LBB1_3
; CHECK-NEXT:  LBB1_10: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB1_4: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB1_12
; CHECK-NEXT:  LBB1_2: ; %entry
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB1_10
; CHECK-NEXT:  LBB1_3: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET
entry:
  %res = call { i16, i1 } @llvm.sadd.with.overflow.i16(i16 %a, i16 %b)
  %ov = extractvalue { i16, i1 } %res, 1
  br i1 %ov, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}

define i8 @br_usub_ov(i8 %a, i8 %b) {
; CHECK-LABEL: br_usub_ov:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    SUB B
; CHECK-NEXT:    JNC LBB2_1
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB2_4
; CHECK-NEXT:  LBB2_3: ; %t
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB2_1:
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JZ LBB2_3
; CHECK-NEXT:  LBB2_4: ; %f
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
entry:
  %res = call { i8, i1 } @llvm.usub.with.overflow.i8(i8 %a, i8 %b)
  %ov = extractvalue { i8, i1 } %res, 1
  br i1 %ov, label %t, label %f

t:
  ret i8 1

f:
  ret i8 0
}
