; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 | FileCheck %s

; PHI node / diamond control flow patterns.
; Adapted from generic RISC-V branch patterns.

; Simple diamond: if-then-else with different values
define i16 @diamond_simple(i16 %a, i16 %b) {
; CHECK-LABEL: diamond_simple:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI D, 1
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA D
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB0_3
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SBB D
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    JC LBB0_5
; CHECK-NEXT:  LBB0_4: ; %entry
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    JMP LBB0_6
; CHECK-NEXT:  LBB0_3: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB0_4
; CHECK-NEXT:  LBB0_5: ; %entry
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:  LBB0_6: ; %entry
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB0_8
; CHECK-NEXT:  ; %bb.7: ; %then
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ADD E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADC D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_8: ; %else
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET
entry:
  %cmp = icmp sgt i16 %a, 0
  br i1 %cmp, label %then, label %else

then:
  %sum = add i16 %a, %b
  br label %merge

else:
  %diff = sub i16 %b, %a
  br label %merge

merge:
  %r = phi i16 [ %sum, %then ], [ %diff, %else ]
  ret i16 %r
}

; Nested diamond: two levels of branching
define i16 @diamond_nested(i16 %a, i16 %b) {
; CHECK-LABEL: diamond_nested:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 65532
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:    LXI D, 1
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA D
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB1_3
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SBB D
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    JC LBB1_5
; CHECK-NEXT:  LBB1_4: ; %entry
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    JMP LBB1_6
; CHECK-NEXT:  LBB1_3: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JZ LBB1_4
; CHECK-NEXT:  LBB1_5: ; %entry
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:  LBB1_6: ; %entry
; CHECK-NEXT:    LXI H, 8
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB1_13
; CHECK-NEXT:  ; %bb.7: ; %positive
; CHECK-NEXT:    LXI H, 101
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRA H
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB1_14
; CHECK-NEXT:  ; %bb.8: ; %positive
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB L
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SBB H
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    JNC LBB1_16
; CHECK-NEXT:  LBB1_9: ; %positive
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB1_17
; CHECK-NEXT:  LBB1_10: ; %large
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ADD E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADC D
; CHECK-NEXT:    JMP LBB1_11
; CHECK-NEXT:  LBB1_13: ; %nonpositive
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, E
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    CALL __mul16
; CHECK-NEXT:    JMP LBB1_12
; CHECK-NEXT:  LBB1_14: ; %positive
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANI 128
; CHECK-NEXT:    JNZ LBB1_9
; CHECK-NEXT:  LBB1_16: ; %positive
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JZ LBB1_10
; CHECK-NEXT:  LBB1_17: ; %small
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SBB D
; CHECK-NEXT:  LBB1_11: ; %large
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:  LBB1_12: ; %large
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967292
; CHECK-NEXT:    RET
entry:
  %cmp1 = icmp sgt i16 %a, 0
  br i1 %cmp1, label %positive, label %nonpositive

positive:
  %cmp2 = icmp sgt i16 %a, 100
  br i1 %cmp2, label %large, label %small

large:
  %r1 = add i16 %a, %b
  br label %done

small:
  %r2 = sub i16 %a, %b
  br label %done

nonpositive:
  %r3 = mul i16 %a, %b
  br label %done

done:
  %r = phi i16 [ %r1, %large ], [ %r2, %small ], [ %r3, %nonpositive ]
  ret i16 %r
}

; Three-way phi (switch-like with phi)
define i8 @three_way_phi(i8 %sel) {
; CHECK-LABEL: three_way_phi:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    MVI B, 10
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    CPI 0
; CHECK-NEXT:    JZ LBB2_3
; CHECK-NEXT:  ; %bb.1: ; %check1
; CHECK-NEXT:    MVI B, 20
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    CPI 1
; CHECK-NEXT:    JZ LBB2_3
; CHECK-NEXT:  ; %bb.2: ; %default
; CHECK-NEXT:    MVI B, 30
; CHECK-NEXT:  LBB2_3: ; %done
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    RET
entry:
  %cmp1 = icmp eq i8 %sel, 0
  br i1 %cmp1, label %case0, label %check1

check1:
  %cmp2 = icmp eq i8 %sel, 1
  br i1 %cmp2, label %case1, label %default

case0:
  br label %done
case1:
  br label %done
default:
  br label %done

done:
  %r = phi i8 [ 10, %case0 ], [ 20, %case1 ], [ 30, %default ]
  ret i8 %r
}
