; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Pointer compares should lower without leaving compare/branch pseudos.

define i8 @ptr_eq(ptr %a, ptr %b) {
; CHECK-LABEL: ptr_eq:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV H, M
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MVI B, 1
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    CMP D
; CHECK-NEXT:    JNZ LBB0_3
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    CMP E
; CHECK-NEXT:    JNZ LBB0_3
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:  ; %bb.4: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_3: ; %entry
; CHECK-NEXT:  ; %bb.5: ; %entry
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    RET
entry:
  %cmp = icmp eq ptr %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}

define i8 @ptr_ult(ptr %a, ptr %b) {
; CHECK-LABEL: ptr_ult:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    JNC LBB1_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB1_2: ; %entry
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
entry:
  %cmp = icmp ult ptr %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}
