; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=i8085-unknown-elf -O0 -stop-after=finalize-isel -o - %s | FileCheck %s

define i64 @ret_i64_sext(i16 %x) {
  %ext = sext i16 %x to i64
  ret i64 %ext
}

; CHECK-LABEL: name: ret_i64_sext
; CHECK-NOT: SRL
; CHECK: RET{{.*}}$iax{{.*}}$ibx
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
