; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs  | FileCheck %s

define void @retvoid(i8* %x) {
; CHECK-LABEL: retvoid:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    RET
  ret void
}


define i8 @reteight() #0 {
; CHECK-LABEL: reteight:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    MVI A, 56
; CHECK-NEXT:    RET
  ret i8 56
}

define i16 @retsixteen() {
; CHECK-LABEL: retsixteen:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    LXI B, 4660
; CHECK-NEXT:    RET
  ret i16 4660
}

define i32 @retthirtytwo() {
; CHECK-LABEL: retthirtytwo:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65532
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MVI M, 4
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 3
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 2
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 1
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    LXI B, 772
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967292
; CHECK-NEXT:    RET
  ret i32 16909060
}

define i64 @retsixtyfour() {
; CHECK-LABEL: retsixtyfour:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65532
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MVI M, 4
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 3
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 2
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 1
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 5
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    LXI H, 7
; CHECK-NEXT:    DAD B
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MVI M, 8
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 7
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 6
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 5
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 1
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967292
; CHECK-NEXT:    RET
  ret i64 72623859790382856
}
