; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Select lowering for i8 should emit control flow and return.

define i8 @select_i8(i8 %a, i8 %b, i1 %c) {
; CHECK-LABEL: select_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JZ LBB0_3
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    DCX H
; CHECK-NEXT:  LBB0_3: ; %entry
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, H
; CHECK-NEXT:    MOV C, L
; CHECK-NEXT:    LDAX B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET
entry:
  %sel = select i1 %c, i8 %a, i8 %b
  ret i8 %sel
}
