; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 | FileCheck %s

; Sign/zero extension chains across type widths.
; Adapted from RISC-V sext-zext-trunc.ll

; zext i1 -> i16
define i16 @zext_i1_to_i16(i1 %a) {
; CHECK-LABEL: zext_i1_to_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    LXI D, 1
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ANA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET
entry:
  %r = zext i1 %a to i16
  ret i16 %r
}

; sext i8 -> i32 (sign extends with ADI 128; SBB A pattern)
define i32 @sext_i8_to_i32(i8 %a) {
; CHECK-LABEL: sext_i8_to_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65532
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    ADI 128
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ADI 128
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967292
; CHECK-NEXT:    RET
entry:
  %r = sext i8 %a to i32
  ret i32 %r
}

; zext i8 -> i32 (fills upper bytes with zero)
define i32 @zext_i8_to_i32(i8 %a) {
; CHECK-LABEL: zext_i8_to_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65532
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, D
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967292
; CHECK-NEXT:    RET
entry:
  %r = zext i8 %a to i32
  ret i32 %r
}

; sext i16 -> i32 (sign extends high byte)
define i32 @sext_i16_to_i32(i16 %a) {
; CHECK-LABEL: sext_i16_to_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65532
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADI 128
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967292
; CHECK-NEXT:    RET
entry:
  %r = sext i16 %a to i32
  ret i32 %r
}

; zext i16 -> i32 (upper 16 bits zeroed)
define i32 @zext_i16_to_i32(i16 %a) {
; CHECK-LABEL: zext_i16_to_i32:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    ; implicit-def: $iax
; CHECK-NEXT:    LXI H, 65532
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV M, C
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV M, B
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MVI M, 0
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    SPHL
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4294967292
; CHECK-NEXT:    RET
entry:
  %r = zext i16 %a to i32
  ret i32 %r
}

; trunc i32 -> i16 (just keep low 16 bits)
define i16 @trunc_i32_to_i16(i32 %a) {
; CHECK-LABEL: trunc_i32_to_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    RET
entry:
  %r = trunc i32 %a to i16
  ret i16 %r
}

; trunc i16 -> i1 (just low bit)
define i1 @trunc_i16_to_i1(i16 %a) {
; CHECK-LABEL: trunc_i16_to_i1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    RET
entry:
  %r = trunc i16 %a to i1
  ret i1 %r
}
