// REQUIRES: i8085-sim
// RUN: %S/../../../../../tooling/build/build-clang-8085/bin/clang -target i8085-unknown-elf -O0 -ffreestanding -fno-builtin -nostdlib -c \
// RUN:   %S/../../../../../sysroot/crt/crt0.S -o %t.crt0.o
// RUN: %S/../../../../../tooling/build/build-clang-8085/bin/clang -target i8085-unknown-elf -O0 -ffreestanding -fno-builtin -nostdlib -emit-llvm -c \
// RUN:   %s -o %t.bc
// RUN: %S/../../../../../tooling/build/build-clang-8085/bin/llc -mtriple=i8085-unknown-elf -filetype=obj %t.bc -o %t.o
// RUN: %S/../../../../../tooling/build/build-clang-8085/bin/ld.lld -m i8085elf \
// RUN:   -T %S/../../../../../sysroot/ldscripts/i8085-32kram-32krom.ld -Map %t.map \
// RUN:   -o %t.elf %t.crt0.o %t.o
// RUN: llvm-objcopy -O binary %t.elf %t.bin
// RUN: %S/../../../../../i8085-trace/build/i8085-trace -S -q -n 200000 \
// RUN:   -d 0x0540:0x10 %t.bin 2>&1 | FileCheck %s --check-prefix=CALLRET

__attribute__((naked)) int main(void) {
  __asm__ volatile(
      "xra a\n"
      "cz call_z\n"
      "lda 0x0540\n"
      "cpi 0x01\n"
      "jz call_z_ok\n"
      "mvi a, 0xee\n"
      "sta 0x0540\n"
      "call_z_ok:\n"
      "mvi a, 0x01\n"
      "ora a\n"
      "cnz call_nz\n"
      "lda 0x0541\n"
      "cpi 0x01\n"
      "jz call_nz_ok\n"
      "mvi a, 0xee\n"
      "sta 0x0541\n"
      "call_nz_ok:\n"
      "stc\n"
      "cc call_c\n"
      "lda 0x0542\n"
      "cpi 0x01\n"
      "jz call_c_ok\n"
      "mvi a, 0xee\n"
      "sta 0x0542\n"
      "call_c_ok:\n"
      "xra a\n"
      "cnc call_nc\n"
      "lda 0x0543\n"
      "cpi 0x01\n"
      "jz call_nc_ok\n"
      "mvi a, 0xee\n"
      "sta 0x0543\n"
      "call_nc_ok:\n"
      "mvi a, 0x01\n"
      "ora a\n"
      "cp call_p\n"
      "lda 0x0544\n"
      "cpi 0x01\n"
      "jz call_p_ok\n"
      "mvi a, 0xee\n"
      "sta 0x0544\n"
      "call_p_ok:\n"
      "mvi a, 0x80\n"
      "ora a\n"
      "cm call_m\n"
      "lda 0x0545\n"
      "cpi 0x01\n"
      "jz call_m_ok\n"
      "mvi a, 0xee\n"
      "sta 0x0545\n"
      "call_m_ok:\n"
      "xra a\n"
      "cpe call_pe\n"
      "lda 0x0546\n"
      "cpi 0x01\n"
      "jz call_pe_ok\n"
      "mvi a, 0xee\n"
      "sta 0x0546\n"
      "call_pe_ok:\n"
      "mvi a, 0x01\n"
      "ora a\n"
      "cpo call_po\n"
      "lda 0x0547\n"
      "cpi 0x01\n"
      "jz call_po_ok\n"
      "mvi a, 0xee\n"
      "sta 0x0547\n"
      "call_po_ok:\n"
      "mvi a, 0x01\n"
      "sta 0x0548\n"
      "call test_rz\n"
      "mvi a, 0x01\n"
      "sta 0x0549\n"
      "call test_rnz\n"
      "mvi a, 0x01\n"
      "sta 0x054A\n"
      "call test_rc\n"
      "mvi a, 0x01\n"
      "sta 0x054B\n"
      "call test_rnc\n"
      "mvi a, 0x01\n"
      "sta 0x054C\n"
      "call test_rp\n"
      "mvi a, 0x01\n"
      "sta 0x054D\n"
      "call test_rm\n"
      "mvi a, 0x01\n"
      "sta 0x054E\n"
      "call test_rpe\n"
      "mvi a, 0x01\n"
      "sta 0x054F\n"
      "call test_rpo\n"
      "hlt\n"
      "call_z:\n"
      "mvi a, 0x01\n"
      "sta 0x0540\n"
      "ret\n"
      "call_nz:\n"
      "mvi a, 0x01\n"
      "sta 0x0541\n"
      "ret\n"
      "call_c:\n"
      "mvi a, 0x01\n"
      "sta 0x0542\n"
      "ret\n"
      "call_nc:\n"
      "mvi a, 0x01\n"
      "sta 0x0543\n"
      "ret\n"
      "call_p:\n"
      "mvi a, 0x01\n"
      "sta 0x0544\n"
      "ret\n"
      "call_m:\n"
      "mvi a, 0x01\n"
      "sta 0x0545\n"
      "ret\n"
      "call_pe:\n"
      "mvi a, 0x01\n"
      "sta 0x0546\n"
      "ret\n"
      "call_po:\n"
      "mvi a, 0x01\n"
      "sta 0x0547\n"
      "ret\n"
      "test_rz:\n"
      "xra a\n"
      "rz\n"
      "mvi a, 0xee\n"
      "sta 0x0548\n"
      "ret\n"
      "test_rnz:\n"
      "mvi a, 0x01\n"
      "ora a\n"
      "rnz\n"
      "mvi a, 0xee\n"
      "sta 0x0549\n"
      "ret\n"
      "test_rc:\n"
      "stc\n"
      "rc\n"
      "mvi a, 0xee\n"
      "sta 0x054A\n"
      "ret\n"
      "test_rnc:\n"
      "xra a\n"
      "rnc\n"
      "mvi a, 0xee\n"
      "sta 0x054B\n"
      "ret\n"
      "test_rp:\n"
      "mvi a, 0x01\n"
      "ora a\n"
      "rp\n"
      "mvi a, 0xee\n"
      "sta 0x054C\n"
      "ret\n"
      "test_rm:\n"
      "mvi a, 0x80\n"
      "ora a\n"
      "rm\n"
      "mvi a, 0xee\n"
      "sta 0x054D\n"
      "ret\n"
      "test_rpe:\n"
      "xra a\n"
      "rpe\n"
      "mvi a, 0xee\n"
      "sta 0x054E\n"
      "ret\n"
      "test_rpo:\n"
      "mvi a, 0x01\n"
      "ora a\n"
      "rpo\n"
      "mvi a, 0xee\n"
      "sta 0x054F\n"
      "ret\n");
}

// CALLRET: Memory dump 0x0540 - 0x054F (16 bytes):
// CALLRET: 0540: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01
// CALLRET: "halt":"hlt"
