; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Switch lowering for i16 should expand to compare/branch chain.

define i16 @switch_i16(i16 %x) {
; CHECK-LABEL: switch_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 258
; CHECK-NEXT:    PUSH H
; CHECK-NEXT:    LXI H, 4
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    POP H
; CHECK-NEXT:    MVI D, 1
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CMP H
; CHECK-NEXT:    JNZ LBB0_6
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    CMP L
; CHECK-NEXT:    JZ LBB0_3
; CHECK-NEXT:  LBB0_6: ; %entry
; CHECK-NEXT:    MVI D, 0
; CHECK-NEXT:  LBB0_3: ; %entry
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB0_4
; CHECK-NEXT:  ; %bb.7: ; %entry
; CHECK-NEXT:    LXI H, 0
; CHECK-NEXT:    MVI D, 1
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CMP H
; CHECK-NEXT:    JNZ LBB0_12
; CHECK-NEXT:  ; %bb.8: ; %entry
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    CMP L
; CHECK-NEXT:    JNZ LBB0_12
; CHECK-NEXT:  ; %bb.10: ; %entry
; CHECK-NEXT:    MVI D, 0
; CHECK-NEXT:  LBB0_12: ; %entry
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB0_14
; CHECK-NEXT:  ; %bb.13: ; %case0
; CHECK-NEXT:    LXI B, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_4: ; %case258
; CHECK-NEXT:    LXI B, 258
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_14: ; %default
; CHECK-NEXT:    LXI B, 1
; CHECK-NEXT:    RET
entry:
  switch i16 %x, label %default [
    i16 0, label %case0
    i16 258, label %case258
  ]

case0:
  ret i16 0

case258:
  ret i16 258

default:
  ret i16 1
}
