; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Switch lowering for i16 should expand to compare/branch chain.

define i16 @switch_i16(i16 %x) {
; CHECK-LABEL: switch_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  LBB0_0:
; CHECK-NEXT:    LXI B, 258
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    MOV H, D
; CHECK-NEXT:    MOV L, E
; CHECK-NEXT:    MVI D, 1
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    CMP B
; CHECK-NEXT:    JNZ LBB0_5
; CHECK-NEXT:  LBB0_1:
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    CMP C
; CHECK-NEXT:    JZ LBB0_6
; CHECK-NEXT:  LBB0_5:
; CHECK-NEXT:    MVI D, 0
; CHECK-NEXT:  LBB0_6:
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ORI 0
; CHECK-NEXT:    JNZ LBB0_13
; CHECK-NEXT:  LBB0_7:
; CHECK-NEXT:    LXI B, 0
; CHECK-NEXT:    MVI D, 1
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    CMP B
; CHECK-NEXT:    JNZ LBB0_12
; CHECK-NEXT:  LBB0_8:
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    CMP C
; CHECK-NEXT:    JNZ LBB0_12
; CHECK-NEXT:  LBB0_10:
; CHECK-NEXT:    MVI D, 0
; CHECK-NEXT:  LBB0_12:
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    ORI 0
; CHECK-NEXT:    JNZ LBB0_14
; CHECK-NEXT:  LBB0_13:
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_14:
; CHECK-NEXT:    LXI B, 1
; CHECK-NEXT:    RET
entry:
  switch i16 %x, label %default [
    i16 0, label %case0
    i16 258, label %case258
  ]

case0:
  ret i16 0

case258:
  ret i16 258

default:
  ret i16 1
}
