; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Switch lowering should expand to a compare/branch chain.

define i8 @switch_i8(i8 %x) {
; CHECK-LABEL: switch_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CPI 9
; CHECK-NEXT:    JZ LBB0_5
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CPI 5
; CHECK-NEXT:    JZ LBB0_4
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CPI 0
; CHECK-NEXT:    JNZ LBB0_6
; CHECK-NEXT:  ; %bb.3: ; %case0
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_4: ; %case5
; CHECK-NEXT:    MVI A, 5
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_5: ; %case9
; CHECK-NEXT:    MVI A, 9
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_6: ; %default
; CHECK-NEXT:    MVI A, 1
; CHECK-NEXT:    RET
entry:
  switch i8 %x, label %default [
    i8 0, label %case0
    i8 5, label %case5
    i8 9, label %case9
  ]

case0:
  ret i8 0

case5:
  ret i8 5

case9:
  ret i8 9

default:
  ret i8 1
}
