; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Larger switch to exercise compare chains.

define i8 @switch_many(i8 %x) {
; CHECK-LABEL: switch_many:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    CPI 8
; CHECK-NEXT:    JNC LBB0_10
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MVI H, 0
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    ADD L
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ADC H
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    LXI B, JTI0_0
; CHECK-NEXT:    MOV A, L
; CHECK-NEXT:    ADD C
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ADC B
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV H, B
; CHECK-NEXT:    MOV L, C
; CHECK-NEXT:    PCHL
; CHECK-NEXT:  LBB0_2: ; %c0
; CHECK-NEXT:    MVI A, 10
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_6: ; %c4
; CHECK-NEXT:    MVI A, 14
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_4: ; %c2
; CHECK-NEXT:    MVI A, 12
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_5: ; %c3
; CHECK-NEXT:    MVI A, 13
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_9: ; %c7
; CHECK-NEXT:    MVI A, 17
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_3: ; %c1
; CHECK-NEXT:    MVI A, 11
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_7: ; %c5
; CHECK-NEXT:    MVI A, 15
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_8: ; %c6
; CHECK-NEXT:    MVI A, 16
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB0_10: ; %default
; CHECK-NEXT:    MVI A, 0
; CHECK-NEXT:    RET
entry:
  switch i8 %x, label %default [
    i8 0, label %c0
    i8 1, label %c1
    i8 2, label %c2
    i8 3, label %c3
    i8 4, label %c4
    i8 5, label %c5
    i8 6, label %c6
    i8 7, label %c7
  ]

c0: ret i8 10
c1: ret i8 11
c2: ret i8 12
c3: ret i8 13
c4: ret i8 14
c5: ret i8 15
c6: ret i8 16
c7: ret i8 17

default:
  ret i8 0
}
