; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=i8085 -O2 < %s | FileCheck %s

define i16 @caller() {
; CHECK-LABEL: caller:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  LBB1_0:
; CHECK-NEXT:    JMP callee
entry:
  %call = tail call i16 @callee()
  ret i16 %call
}

define i16 @callee() {
; CHECK-LABEL: callee:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  LBB0_0:
; CHECK-NEXT:    LXI B, 7
; CHECK-NEXT:    RET
entry:
  ret i16 7
}

; CHECK-LABEL: caller:
; CHECK-NOT: CALL
; CHECK: JMP callee
; CHECK-LABEL: callee:
